version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
